service: poll-tweet-__SERVERLESS_USER__

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  memorySize: 128
  stage: ${env:SERVERLESS_STAGE}
  region: ${env:AWS_REGION}
  tags:
    project: sls-demo-__SERVERLESS_USER__
    owner: __SERVERLESS_USER__
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: "arn:aws:s3:::${env:TWITTER_STATE_BUCKET}/*"
    - Effect: Allow
      Action:
        - kinesis:DescribeStream
        - kinesis:DescribeSummary
        - kinesis:GetRecords
        - kinesis:PutRecord
        - kinesis:PutRecords
        - kinesis:GetShardIterator
      Resource: ${env:AWS_EVENT_STREAM_ARN_POLL_TWEET}
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Query
        - dynamodb:Scan
      Resource: arn:aws:dynamodb:${env:AWS_REGION}:${env:AWS_ACCOUNT_ID}:table/${env:TWITTER_STATE_TABLE}

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  poll:
    handler: bin/poll
    memorySize: 128
    environment:
      SERVERLESS_USER: ${env:SERVERLESS_USER}
      TWITTER_ACCESS_TOKEN: ${ssm:/aws/reference/secretsmanager/sls-demo-__SERVERLESS_USER__/twitter/access-token~true}
      TWITTER_ACCESS_SECRET: ${ssm:/aws/reference/secretsmanager/sls-demo-__SERVERLESS_USER__/twitter/access-secret~true}
      TWITTER_CONSUMER_KEY: ${ssm:/aws/reference/secretsmanager/sls-demo-__SERVERLESS_USER__/twitter/consumer-key~true}
      TWITTER_CONSUMER_SECRET: ${ssm:/aws/reference/secretsmanager/sls-demo-__SERVERLESS_USER__/twitter/consumer-secret~true}
      AWS_EVENT_STREAM_NAME: ${env:AWS_EVENT_STREAM_NAME_POOL_TWEET}
      TWITTER_STATE_BUCKET: ${env:TWITTER_STATE_BUCKET}
      TWITTER_STATE_FILE: ${env:TWITTER_STATE_FILE}
      TWITTER_QUERY_TIMEOUT_SEC: ${env:TWITTER_QUERY_TIMEOUT_SEC}
      TWITTER_STATE_TYPE: ${env:TWITTER_STATE_TYPE}
      TWITTER_STATE_TABLE: ${env:TWITTER_STATE_TABLE}
    events:
      - schedule: rate(1 minute)

resources:
  Resources:
    workStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: ${env:AWS_EVENT_STREAM_NAME_POLL_TWEET}
        ShardCount: 1
