# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: poll-tweet 

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  stage: ${env:SERVERLESS_STAGE}
  region: ${env:AWS_REGION}
  tags:
    project: serverless-demo
    owner: oliver.koeth@nttdata.com
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::${self:provider.stage}-serverless-demo-twitter-state/*"

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  poll:
    handler: bin/poll
    environment:
      TWITTER_ACCESS_TOKEN: ${ssm:/aws/reference/secretsmanager/serverless-demo/twitter/access-token~true}
      TWITTER_ACCESS_SECRET: ${ssm:/aws/reference/secretsmanager/serverless-demo/twitter/access-secret~true}
      TWITTER_CONSUMER_KEY: ${ssm:/aws/reference/secretsmanager/serverless-demo/twitter/consumer-key~true}
      TWITTER_CONSUMER_SECRET: ${ssm:/aws/reference/secretsmanager/serverless-demo/twitter/consumer-secret~true}
      TWITTER_STATE_BUCKET: ${self:provider.stage}-serverless-demo-twitter-state
    events:
      - schedule: rate(1 minute)

resources:
  Resources:
    TwitterStateBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.stage}-serverless-demo-twitter-state
        Tags: 
          - Key: project
            Value: serverless-demo
          - Key: owner
            Value: oliver.koeth@nttdata.com
    TwitterAccessToken:
      Type: "AWS::SecretsManager::Secret"
      Properties:
        Name: serverless-demo/twitter/access-token
        Description: Access Token for serverless-demo Twitter app
        SecretString: ${env:TWITTER_ACCESS_TOKEN}
        Tags: 
          - Key: project
            Value: serverless-demo
          - Key: owner
            Value: oliver.koeth@nttdata.com
    TwitterAccessSecret:
      Type: "AWS::SecretsManager::Secret"
      Properties:
        Name: serverless-demo/twitter/access-secret
        Description: Access Secret for serverless-demo Twitter app
        SecretString: ${env:TWITTER_ACCESS_SECRET}
        Tags: 
          - Key: project
            Value: serverless-demo
          - Key: owner
            Value: oliver.koeth@nttdata.com
    TwitterConsumerKey:
      Type: "AWS::SecretsManager::Secret"
      Properties:
        Name: serverless-demo/twitter/consumer-key
        Description: Consumer Key for serverless-demo Twitter app
        SecretString: ${env:TWITTER_CONSUMER_KEY}
        Tags: 
          - Key: project
            Value: serverless-demo
          - Key: owner
            Value: oliver.koeth@nttdata.com
    TwitterConsumerSecret:
      Type: "AWS::SecretsManager::Secret"
      Properties:
        Name: serverless-demo/twitter/consumer-secret
        Description: Consumer Secret for serverless-demo Twitter app
        SecretString: ${env:TWITTER_CONSUMER_SECRET}
        Tags: 
          - Key: project
            Value: serverless-demo
          - Key: owner
            Value: oliver.koeth@nttdata.com
