# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: poll-tweet 

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  stage: ${env:SERVERLESS_STAGE}
  region: ${env:AWS_REGION}
  tags:
    project: serverless-demo
    owner: oliver.koeth@nttdata.com
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: "arn:aws:s3:::${self:provider.stage}-serverless-demo-twitter-state/*"
    - Effect: Allow
      Action:
        - kinesis:DescribeStream
        - kinesis:DescribeSummary
        - kinesis:GetRecords
        - kinesis:PutRecord
        - kinesis:PutRecords
        - kinesis:GetShardIterator
      Resource: ${env:AWS_EVENT_STREAM_ARN}

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  poll:
    handler: bin/poll
    memorySize: 128
    environment:
      TWITTER_ACCESS_TOKEN: ${ssm:/aws/reference/secretsmanager/serverless-demo/twitter/access-token~true}
      TWITTER_ACCESS_SECRET: ${ssm:/aws/reference/secretsmanager/serverless-demo/twitter/access-secret~true}
      TWITTER_CONSUMER_KEY: ${ssm:/aws/reference/secretsmanager/serverless-demo/twitter/consumer-key~true}
      TWITTER_CONSUMER_SECRET: ${ssm:/aws/reference/secretsmanager/serverless-demo/twitter/consumer-secret~true}
      AWS_EVENT_STREAM_NAME: ${env:AWS_EVENT_STREAM_NAME}
      TWITTER_STATE_BUCKET: ${self:provider.stage}-serverless-demo-twitter-state
      TWITTER_STATE_FILE: ${env:TWITTER_STATE_FILE}
    events:
      - schedule: rate(5 minutes)
