service: poll-state

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: eu-central-1
  tags:
    project: sls-demo-aboczek
    owner: aboczek
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: "arn:aws:s3:::${env:TWITTER_STATE_BUCKET}/*"
  environment:
    TWITTER_STATE_BUCKET: ${env:TWITTER_STATE_BUCKET}
    TWITTER_STATE_FILE: ${env:TWITTER_STATE_FILE}

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  read:
    handler: bin/read
    events:
      - http:
          path: state
          method: get
  update:
    handler: bin/update
    events:
      - http:
          path: state
          method: put
