service: collect-buzzwords-__SERVERLESS_USER__

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  memorySize: 128
  stage: ${env:SERVERLESS_STAGE}
  region: ${env:AWS_REGION}
  stackTags:
    project: sls-demo-__SERVERLESS_USER__
    owner: __SERVERLESS_USER__
  iamRoleStatements:
    - Effect: Allow
      Action:
        - kinesis:DescribeStream
        - kinesis:DescribeSummary
        - kinesis:GetRecords
        - kinesis:GetShardIterator
      Resource: ${env:AWS_EVENT_STREAM_ARN_POLL_TWEET}
    - Effect: Allow
      Action:
        - kinesis:DescribeStream
        - kinesis:DescribeSummary
        - kinesis:GetRecords
        - kinesis:PutRecord
        - kinesis:PutRecords
        - kinesis:GetShardIterator
      Resource: ${env:AWS_EVENT_STREAM_ARN_COLLECT_BUZZWORDS}

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  collect:
    handler: bin/collect
    environment:
      AWS_EVENT_STREAM_NAME: ${env:AWS_EVENT_STREAM_NAME_COLLECT_BUZZWORDS}
    events:
      - stream:
          type: kinesis
          arn: ${env:AWS_EVENT_STREAM_ARN_POLL_TWEET}
          batchSize: 10
          startingPosition: TRIM_HORIZON
          enabled: true

resources:
  Resources:
    eventStreamCollectBuzzwords:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: ${env:AWS_EVENT_STREAM_NAME_COLLECT_BUZZWORDS}
        ShardCount: 1
