service: persist-aggregates-__SERVERLESS_USER__

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  memorySize: 128
  stage: ${env:SERVERLESS_STAGE}
  region: ${env:AWS_REGION}
  stackTags:
    project: sls-demo-__SERVERLESS_USER__
    owner: __SERVERLESS_USER__
  iamRoleStatements:
    - Effect: Allow
      Action:
        - kinesis:DescribeStream
        - kinesis:DescribeSummary
        - kinesis:GetRecords
        - kinesis:GetShardIterator
      Resource: ${env:AWS_EVENT_STREAM_ARN_COLLECT_BUZZWORDS}
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
  environment:
    SERVERLESS_USER: ${env:SERVERLESS_USER}
    BUZZWORD_AGGREGATES_TABLE: ${env:BUZZWORD_AGGREGATES_TABLE}
    SERVERLESS_STAGE: ${env:SERVERLESS_STAGE}

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  persist:
    handler: bin/persist
    events:
      - stream:
          type: kinesis
          arn: ${env:AWS_EVENT_STREAM_ARN_COLLECT_BUZZWORDS}
          batchSize: 10
          startingPosition: TRIM_HORIZON
          enabled: true
  readall:
    handler: bin/readall
  read:
    handler: bin/read

resources:
  Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:BUZZWORD_AGGREGATES_TABLE}
        AttributeDefinitions:
          - AttributeName: buzzword_namespace
            AttributeType: S
          - AttributeName: version
            AttributeType: N
        KeySchema:
          - AttributeName: buzzword_namespace
            KeyType: HASH
          - AttributeName: version
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    DynamoDbIamPolicy:
      Type: AWS::IAM::Policy
      DependsOn: DynamoDbTable
      Properties:
        PolicyName: lambda-dynamodb
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource: arn:aws:dynamodb:${env:AWS_REGION}:${env:AWS_ACCOUNT_ID}:table/${env:BUZZWORD_AGGREGATES_TABLE}
        Roles:
          - Ref: IamRoleLambdaExecution

